# Generated by Django 3.2.5 on 2022-06-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='situacao',
            field=models.CharField(choices=[('1', 'Disponível'), ('2', 'Em falta'), ('3', 'Retirada do estoque')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='produto',
            name='qnt_em_estoque',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade em estoque'),
        ),
    ]
